apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: auth

images:
- name: auth-srv-main
  newName: blgianinis/auth-srv-main
  newTag: 26c2b128042dbf6e8e18eec1297d1cabd368e767
